version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data: /var/lib/postgresql/data/pgdata
