# Generated by Django 4.2.6 on 2023-10-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(max_length=255, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'порода',
                'verbose_name_plural': 'породы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='кличка')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='фотография')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='почта')),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.breed')),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'собаки',
                'ordering': ('nickname',),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='кличка')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.breed', verbose_name='порода')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dog', verbose_name='собака')),
            ],
        ),
    ]
