# Generated by Django 4.2.6 on 2023-11-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('name',), 'verbose_name': 'собака', 'verbose_name_plural': 'собаки'},
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='nickname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog', to='main.breed'),
        ),
    ]
