# Generated by Django 4.2.6 on 2023-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='для всех'),
        ),
    ]
