# Generated by Django 4.2.7 on 2023-11-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dog_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='стоимость'),
        ),
    ]
